apiVersion: apps/v1
kind: Deployment
metadata:
  name: travelapp
  namespace: dev
spec:
  replicas: 4 
  selector:
    matchLabels:
      app: travelapp
  template:
    metadata:
      labels:
        app: travelapp
    spec:
      containers:
        - name: travel
          image: docker.io/koushik0802/travel:2.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "200m"
